### PR TITLE
Fix Libdl dependency issue.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Hmm https://github.com/fredrikekre/CodecZlib.jl/blob/0d59c95781b972aefd834ed4f413cab9ce208126/src/CodecZlib.jl#L38 is already in there...

**Comment by bicycle1885** [comment]
What issue does this solve? Why this is better than `using Compad.Libdl` is not clear to me...

**Comment by KristofferC** [comment]
The problem is:

1) Stdlibs need to be declared as dependencies to load on 0.7+
2) Stdlibs cannot be in REQUIRE files
3) The new registry is converted from METADATA for the time being 
4) To deal with 1), the source code is parsed for `using Stdlib` statements and those are added to the deps in the new registry
5) BinaryProvider injects a `using Libdl` into packages.
6) So this package needs a `Libdl` in the dependencies. This PR fixes that.

**Comment by bicycle1885** [comment]
I see. I think `using Compat.Stdlib` should be parsed as well but I'm not sure. Anyway, thank you for the pull request and explanation.

**Pull request merged**
