### PR TITLE
update binaries

### PR DESCRIPTION
**Pull request by bicycle1885**

### CODE REVIEW

**Comment by bicycle1885** [comment]
Windows... 😭

**Comment by visr** [comment]
FWIW, this works for me on Win64 0.7. Maybe restart the build?

```
Julia Version 0.7.0-beta.108
Commit 3ac99765de (2018-07-01 22:57 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```
```julia
(v0.7) pkg> test CodecZlib
   Testing CodecZlib
 Resolving package versions...
Test Summary: | Pass  Total
Gzip Codec    |  538    538
Test Summary: | Pass  Total
Zlib Codec    |  529    529
Test Summary: | Pass  Total
Deflate Codec |  501    501
┌ Warning: `mapfoldl(f, op, v0, itr)` is deprecated, use `mapfoldl(f, op, itr; init=v0)` instead.
│   caller = test_chunked_read(::Type, ::Type) at testtools.jl:86
└ @ TranscodingStreams testtools.jl:86
Test Summary:      | Pass  Total
TranscodingStreams | 1028   1028
   Testing CodecZlib tests passed
```

**Comment by bicycle1885** [comment]
I tried it again but still see the same error. This may be due to lack of memory on AppVeyor (https://stackoverflow.com/a/23444925/1243761).

**Comment by visr** [comment]
Oh that is odd, I don't see anything large being processed in the tests...

**Comment by bicycle1885** [comment]
Superseded by #30.

**Pull request closed without merging**
