### PR TITLE
use Zlib_jll instead of deps/build.jl

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Lol, the same PR has been made three times, once by @staticfloat, @KristofferC and now me.

**Comment by KristofferC** [comment]
Lol! :man_facepalming: :man_facepalming:

**Comment by JackDunnNZ** [comment]
Bump, any chance this can be merged?

**Comment by KristofferC** [comment]
Merged https://github.com/JuliaIO/CodecZlib.jl/pull/49 instead since it also updated AppVeyor.

**Pull request closed without merging**
